import type { Theme } from '../types';

export const themes: Theme[] = [
  // ── 1. 默认纯净 ──────────────────────────────────────────────
  {
    id: 'default',
    name: '默认纯净',
    emoji: '📄',
    description: '经典白底黑字，适合大多数文章',
    colors: {
      background: '#ffffff',
      text: '#333333',
      h1: '#1a1a1a',
      h2: '#1a1a1a',
      h3: '#2d2d2d',
      h4: '#2d2d2d',
      h5: '#333333',
      h6: '#333333',
      bold: '#1a1a1a',
      italic: '#555555',
      strikethrough: '#999999',
      link: '#576b95',
      inlineCode: '#e74c3c',
      inlineCodeBg: '#f5f5f5',
      codeBlockBg: '#f6f8fa',
      codeBlockText: '#24292e',
      blockquoteBorder: '#dfe2e5',
      blockquoteBg: '#f8f8f8',
      blockquoteText: '#6a737d',
      listBullet: '#576b95',
      tableBorder: '#dfe2e5',
      tableHeaderBg: '#f6f8fa',
      tableHeaderText: '#24292e',
      tableStripe: '#f9f9f9',
      hr: '#e1e4e8',
      footnoteLink: '#576b95',
      footnoteText: '#6a737d',
      paragraphSpacing: '1.2em',
      headingMarginTop: '1.5em',
      headingMarginBottom: '0.8em',
    },
    style: {
      fontFamily:
        '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "PingFang SC", "Microsoft YaHei", sans-serif',
      fontSize: '15px',
      lineHeight: 1.8,
      borderRadius: '4px',
      codeFontFamily:
        'Menlo, Monaco, Consolas, "Courier New", monospace',
    },
  },

  // ── 2. 文艺浅调 ──────────────────────────────────────────────
  {
    id: 'literary',
    name: '文艺浅调',
    emoji: '🌸',
    description: '温暖米白底，淡粉引用块，适合散文随笔',
    colors: {
      background: '#fdfbf7',
      text: '#5a4e42',
      h1: '#3d3529',
      h2: '#3d3529',
      h3: '#4a4035',
      h4: '#4a4035',
      h5: '#5a4e42',
      h6: '#5a4e42',
      bold: '#3d3529',
      italic: '#7a6a5a',
      strikethrough: '#b0a090',
      link: '#c17878',
      inlineCode: '#b06050',
      inlineCodeBg: '#f5ebe4',
      codeBlockBg: '#f0e6dc',
      codeBlockText: '#5a4030',
      blockquoteBorder: '#e0a0a0',
      blockquoteBg: '#faf0f0',
      blockquoteText: '#8a6060',
      listBullet: '#c17878',
      tableBorder: '#e0d0c0',
      tableHeaderBg: '#f0e6dc',
      tableHeaderText: '#5a4030',
      tableStripe: '#f5ede6',
      hr: '#e0d0c0',
      footnoteLink: '#c17878',
      footnoteText: '#9a8070',
      paragraphSpacing: '1.4em',
      headingMarginTop: '1.8em',
      headingMarginBottom: '1em',
    },
    style: {
      fontFamily:
        '"Noto Serif SC", "Songti SC", "SimSun", Georgia, serif',
      fontSize: '16px',
      lineHeight: 2,
      borderRadius: '2px',
      codeFontFamily:
        '"Fira Code", Menlo, monospace',
    },
  },

  // ── 3. 深阅读 ────────────────────────────────────────────────
  {
    id: 'deep-reading',
    name: '深阅读',
    emoji: '📖',
    description: '护眼羊皮纸色，墨绿标题，适合长文深度阅读',
    colors: {
      background: '#f4f0e4',
      text: '#3a3528',
      h1: '#2a4a2a',
      h2: '#2a4a2a',
      h3: '#3a5a3a',
      h4: '#3a5a3a',
      h5: '#4a6a4a',
      h6: '#4a6a4a',
      bold: '#2a4a2a',
      italic: '#6a7a5a',
      strikethrough: '#a0a090',
      link: '#4a7a4a',
      inlineCode: '#5a8a5a',
      inlineCodeBg: '#e8f0e0',
      codeBlockBg: '#2d3a2d',
      codeBlockText: '#c8d8c0',
      blockquoteBorder: '#8aaa80',
      blockquoteBg: '#e8f0e0',
      blockquoteText: '#5a7a5a',
      listBullet: '#5a8a5a',
      tableBorder: '#b8c8b0',
      tableHeaderBg: '#d8e8d0',
      tableHeaderText: '#2a4a2a',
      tableStripe: '#e8f0e0',
      hr: '#b8c8b0',
      footnoteLink: '#5a8a5a',
      footnoteText: '#7a9a7a',
      paragraphSpacing: '1.5em',
      headingMarginTop: '2em',
      headingMarginBottom: '1em',
    },
    style: {
      fontFamily:
        '"Noto Serif SC", "Source Han Serif CN", Georgia, serif',
      fontSize: '16px',
      lineHeight: 2,
      borderRadius: '0px',
      codeFontFamily:
        '"Source Code Pro", Menlo, monospace',
    },
  },

  // ── 4. 商务简雅 ──────────────────────────────────────────────
  {
    id: 'business',
    name: '商务简雅',
    emoji: '💼',
    description: '深蓝主调，专业干练，适合商业分析行业报告',
    colors: {
      background: '#ffffff',
      text: '#2c3e50',
      h1: '#1a252f',
      h2: '#1a252f',
      h3: '#2c3e50',
      h4: '#34495e',
      h5: '#34495e',
      h6: '#5d6d7e',
      bold: '#1a252f',
      italic: '#5d6d7e',
      strikethrough: '#aab7b8',
      link: '#2471a3',
      inlineCode: '#1a5276',
      inlineCodeBg: '#eaf2f8',
      codeBlockBg: '#1a252f',
      codeBlockText: '#85c1e9',
      blockquoteBorder: '#2471a3',
      blockquoteBg: '#eaf2f8',
      blockquoteText: '#2c3e50',
      listBullet: '#2471a3',
      tableBorder: '#aeb6bf',
      tableHeaderBg: '#2c3e50',
      tableHeaderText: '#ffffff',
      tableStripe: '#f4f6f7',
      hr: '#d5dbdb',
      footnoteLink: '#2471a3',
      footnoteText: '#7f8c8d',
      paragraphSpacing: '1em',
      headingMarginTop: '1.3em',
      headingMarginBottom: '0.7em',
    },
    style: {
      fontFamily:
        '"Inter", "Helvetica Neue", Arial, "PingFang SC", "Microsoft YaHei", sans-serif',
      fontSize: '15px',
      lineHeight: 1.7,
      borderRadius: '6px',
      codeFontFamily:
        '"JetBrains Mono", Menlo, monospace',
    },
  },

  // ── 5. 科技极简 ──────────────────────────────────────────────
  {
    id: 'tech',
    name: '科技极简',
    emoji: '⚡',
    description: 'GitHub 风格，紧凑排版，代码达人首选',
    colors: {
      background: '#ffffff',
      text: '#24292e',
      h1: '#0d1117',
      h2: '#0d1117',
      h3: '#24292e',
      h4: '#24292e',
      h5: '#586069',
      h6: '#586069',
      bold: '#0d1117',
      italic: '#6a737d',
      strikethrough: '#959da5',
      link: '#0366d6',
      inlineCode: '#e36209',
      inlineCodeBg: '#fff3cd',
      codeBlockBg: '#f6f8fa',
      codeBlockText: '#24292e',
      blockquoteBorder: '#d1d5da',
      blockquoteBg: '#f6f8fa',
      blockquoteText: '#6a737d',
      listBullet: '#0366d6',
      tableBorder: '#dfe2e5',
      tableHeaderBg: '#f6f8fa',
      tableHeaderText: '#24292e',
      tableStripe: '#ffffff',
      hr: '#e1e4e8',
      footnoteLink: '#0366d6',
      footnoteText: '#6a737d',
      paragraphSpacing: '1em',
      headingMarginTop: '1.2em',
      headingMarginBottom: '0.6em',
    },
    style: {
      fontFamily:
        '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif',
      fontSize: '14px',
      lineHeight: 1.6,
      borderRadius: '3px',
      codeFontFamily:
        '"SF Mono", "Fira Code", Menlo, Consolas, monospace',
    },
  },

  // ── 6. 萌趣手账 ──────────────────────────────────────────────
  {
    id: 'cute',
    name: '萌趣手账',
    emoji: '🎀',
    description: '奶油橙暖底，圆润可爱，适合生活分享日记',
    colors: {
      background: '#fff8f0',
      text: '#5a4a3a',
      h1: '#e07050',
      h2: '#e07050',
      h3: '#d4856a',
      h4: '#d4856a',
      h5: '#c07050',
      h6: '#c07050',
      bold: '#e06040',
      italic: '#a08070',
      strikethrough: '#c0b0a0',
      link: '#e07050',
      inlineCode: '#e07050',
      inlineCodeBg: '#ffe8d8',
      codeBlockBg: '#3a2a20',
      codeBlockText: '#f0c0a0',
      blockquoteBorder: '#f0c0a0',
      blockquoteBg: '#fff0e0',
      blockquoteText: '#8a7060',
      listBullet: '#e07050',
      tableBorder: '#f0d0b0',
      tableHeaderBg: '#ffe8d8',
      tableHeaderText: '#5a4a3a',
      tableStripe: '#fff0e0',
      hr: '#f0d0b0',
      footnoteLink: '#e07050',
      footnoteText: '#a09080',
      paragraphSpacing: '1.3em',
      headingMarginTop: '1.6em',
      headingMarginBottom: '0.8em',
    },
    style: {
      fontFamily:
        '"Nunito", "Quicksand", "PingFang SC", "Microsoft YaHei", sans-serif',
      fontSize: '15px',
      lineHeight: 1.9,
      borderRadius: '12px',
      codeFontFamily:
        '"Fira Code", "Comic Mono", Menlo, monospace',
    },
  },

  // ── 7. 灰度杂志 ──────────────────────────────────────────────
  {
    id: 'magazine',
    name: '灰度杂志',
    emoji: '🗞️',
    description: '高对比度黑白，衬线字体，杂志级排版质感',
    colors: {
      background: '#fafafa',
      text: '#333333',
      h1: '#000000',
      h2: '#000000',
      h3: '#1a1a1a',
      h4: '#1a1a1a',
      h5: '#333333',
      h6: '#333333',
      bold: '#000000',
      italic: '#555555',
      strikethrough: '#aaaaaa',
      link: '#333333',
      inlineCode: '#000000',
      inlineCodeBg: '#eeeeee',
      codeBlockBg: '#1a1a1a',
      codeBlockText: '#e0e0e0',
      blockquoteBorder: '#000000',
      blockquoteBg: '#f5f5f5',
      blockquoteText: '#444444',
      listBullet: '#000000',
      tableBorder: '#333333',
      tableHeaderBg: '#000000',
      tableHeaderText: '#ffffff',
      tableStripe: '#f0f0f0',
      hr: '#000000',
      footnoteLink: '#333333',
      footnoteText: '#666666',
      paragraphSpacing: '1.5em',
      headingMarginTop: '2em',
      headingMarginBottom: '1em',
    },
    style: {
      fontFamily:
        '"Playfair Display", "Noto Serif SC", "Songti SC", Georgia, serif',
      fontSize: '17px',
      lineHeight: 1.85,
      borderRadius: '0px',
      codeFontFamily:
        '"IBM Plex Mono", Menlo, monospace',
    },
  },

  // ── 8. 墨夜星辰 ──────────────────────────────────────────────
  {
    id: 'starry-night',
    name: '墨夜星辰',
    emoji: '🌌',
    description: '深邃星空蓝紫调，霓虹点缀，科技感与浪漫并存',
    colors: {
      background: '#0d1117',
      text: '#c9d1d9',
      h1: '#f0f6fc',
      h2: '#f0f6fc',
      h3: '#e6edf3',
      h4: '#e6edf3',
      h5: '#c9d1d9',
      h6: '#8b949e',
      bold: '#f0f6fc',
      italic: '#a0c4e8',
      strikethrough: '#484f58',
      link: '#58a6ff',
      inlineCode: '#f0883e',
      inlineCodeBg: '#1c2128',
      codeBlockBg: '#161b22',
      codeBlockText: '#c9d1d9',
      blockquoteBorder: '#30363d',
      blockquoteBg: '#161b22',
      blockquoteText: '#8b949e',
      listBullet: '#58a6ff',
      tableBorder: '#30363d',
      tableHeaderBg: '#161b22',
      tableHeaderText: '#c9d1d9',
      tableStripe: '#0d1117',
      hr: '#21262d',
      footnoteLink: '#58a6ff',
      footnoteText: '#8b949e',
      paragraphSpacing: '1.3em',
      headingMarginTop: '1.6em',
      headingMarginBottom: '0.8em',
    },
    style: {
      fontFamily:
        '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      fontSize: '15px',
      lineHeight: 1.8,
      borderRadius: '6px',
      codeFontFamily:
        '"Cascadia Code", "Fira Code", Menlo, monospace',
    },
  },

  // ── 9. 森林日记 ──────────────────────────────────────────────
  {
    id: 'forest',
    name: '森林日记',
    emoji: '🌿',
    description: '清新叶绿配色，自然舒适，适合户外旅行生活',
    colors: {
      background: '#f6fbf6',
      text: '#2d4a2d',
      h1: '#1a4a1a',
      h2: '#1a4a1a',
      h3: '#2d5a2d',
      h4: '#2d5a2d',
      h5: '#3d6a3d',
      h6: '#3d6a3d',
      bold: '#1a4a1a',
      italic: '#5a8a5a',
      strikethrough: '#a0c0a0',
      link: '#2d8a2d',
      inlineCode: '#3a7a3a',
      inlineCodeBg: '#e4f5e4',
      codeBlockBg: '#1a2e1a',
      codeBlockText: '#a0d0a0',
      blockquoteBorder: '#6aaa6a',
      blockquoteBg: '#e4f5e4',
      blockquoteText: '#4a7a4a',
      listBullet: '#3a9a3a',
      tableBorder: '#b0d0b0',
      tableHeaderBg: '#d0e8d0',
      tableHeaderText: '#1a4a1a',
      tableStripe: '#e8f5e8',
      hr: '#c0e0c0',
      footnoteLink: '#3a9a3a',
      footnoteText: '#6a9a6a',
      paragraphSpacing: '1.3em',
      headingMarginTop: '1.6em',
      headingMarginBottom: '0.8em',
    },
    style: {
      fontFamily:
        '"Nunito", "Quicksand", "PingFang SC", "Microsoft YaHei", sans-serif',
      fontSize: '15px',
      lineHeight: 1.85,
      borderRadius: '8px',
      codeFontFamily:
        '"Fira Code", Menlo, monospace',
    },
  },

  // ── 10. 暖阳笔记 ─────────────────────────────────────────────
  {
    id: 'warm-sunshine',
    name: '暖阳笔记',
    emoji: '☀️',
    description: '焦糖琥珀暖调，复古质感，适合美食旅行生活',
    colors: {
      background: '#fffaf0',
      text: '#4a3828',
      h1: '#8b4513',
      h2: '#8b4513',
      h3: '#a0522d',
      h4: '#a0522d',
      h5: '#b8651a',
      h6: '#b8651a',
      bold: '#8b4513',
      italic: '#a08060',
      strikethrough: '#c0a888',
      link: '#c87020',
      inlineCode: '#c87020',
      inlineCodeBg: '#fff0d8',
      codeBlockBg: '#2a1a0a',
      codeBlockText: '#e8c090',
      blockquoteBorder: '#e0a060',
      blockquoteBg: '#fff5e8',
      blockquoteText: '#8a6a4a',
      listBullet: '#c87020',
      tableBorder: '#e0c0a0',
      tableHeaderBg: '#ffe8cc',
      tableHeaderText: '#4a3828',
      tableStripe: '#fff5e8',
      hr: '#e0c0a0',
      footnoteLink: '#c87020',
      footnoteText: '#a09070',
      paragraphSpacing: '1.4em',
      headingMarginTop: '1.8em',
      headingMarginBottom: '0.9em',
    },
    style: {
      fontFamily:
        '"Lora", "Noto Serif SC", Georgia, serif',
      fontSize: '16px',
      lineHeight: 1.9,
      borderRadius: '4px',
      codeFontFamily:
        '"Fira Code", Menlo, monospace',
    },
  },
];

export function getThemeById(id: string): Theme {
  return themes.find((t) => t.id === id) ?? themes[0];
}
